use_frameworks!

platform :ios, '8.0'

target 'XNDynamicConfigurationTable_Example' do
  pod 'XNDynamicConfigurationTable', :path => '../'

  target 'XNDynamicConfigurationTable_Tests' do
    inherit! :search_paths

    
  end
end
